version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: learningchinese_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: learning_chinese
    ports:
      - "5432:5432"
    volumes:
      - pgdata_learningchinese:/var/lib/postgresql/data
volumes:
  pgdata_learningchinese:
    driver: local

